name: huungry
description: "Hungry APP"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  shimmer: ^3.0.0
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  image_picker: ^1.2.0
  animate_icons: ^2.0.0
  skeletonizer: ^2.1.0+1
  go_router: ^16.2.5
  flutter_secure_storage: ^9.2.4
  talker_dio_logger: ^5.0.2
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  injectable: ^2.5.1
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.7
  firebase_core: ^4.4.0

dev_dependencies:

  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.12.0
  flutter_gen_core: ^5.12.0
  flutter_lints: ^5.0.0
  injectable_generator: ^2.1.0
  flutter_launcher_icons: ^0.14.4
  intl_utils: ^2.8.3




flutter_gen:
  output: lib/core/assets
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/splash/
    - assets/test/
    - assets/detail/
    - assets/icon/
    - assets/banner/
